version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: 
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.prod.sh
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery --app=config worker -l INFO
    volumes:
      - ${PWD}:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq
      - web
  
  db:
    image: postgres:16-bullseye
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data/
    env_file:
      - ./.env.database
    ports:
      - 5431:5432

volumes:
  postgres_data_stage: