version: '3.8'
services:
  web:
    image: keinermendoza/educayemprende:lite-v1.0.0
    command: 
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.prod.sh
         gunicorn config.wsgi:application --bind 0.0.0.0:8001
    ports:
      - 8001:8001
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:16-bullseye
    volumes:
      - postgres_educa_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.database


volumes:
  postgres_educa_data_prod: