# Generated by Django 5.0.7 on 2024-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='description',
            field=models.JSONField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
