# Generated by Django 5.0.7 on 2024-07-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categories',
            field=models.ManyToManyField(related_name='cursos', to='core.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sub_categories',
            field=models.ManyToManyField(related_name='cursos', to='core.subcategory', verbose_name='Sub Categoría'),
        ),
    ]
