# Generated by Django 5.0.7 on 2024-07-17 14:34

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_curso_categories_curso_sub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title']),
        ),
    ]
