# Generated by Django 5.0.7 on 2024-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_curso_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='summary',
            field=models.CharField(blank=True, max_length=152, null=True, verbose_name='Resumen'),
        ),
    ]
