# Generated by Django 5.0.7 on 2024-07-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_subcategory_topic_remove_curso_sub_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AddField(
            model_name='curso',
            name='topics',
            field=models.ManyToManyField(related_name='cursos', to='core.topic', verbose_name='Temas'),
        ),
    ]
