# Generated by Django 5.0.7 on 2024-07-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_topic_options_curso_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cursos_images')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_curso', to='core.curso')),
            ],
        ),
    ]
