# Generated by Django 5.0.7 on 2024-07-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_imagecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='topics',
            field=models.ManyToManyField(null=True, related_name='cursos', to='core.topic', verbose_name='Temas'),
        ),
    ]
