# Generated by Django 5.0.7 on 2024-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_curso_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='cursos', to='core.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='cursos', to='core.topic', verbose_name='Temas'),
        ),
    ]
